FROM nginx

# We need some custom nginx configuration, which we import here
# You can even configure more if you use a nginx.conf.sigil file (http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-the-nginx-configuration)
# COPY nginx/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template

# Copy our production build from the first step to nginx's html directory
WORKDIR /app

COPY nginx/test.html .

EXPOSE 8080
